In [1]:
import numpy as np
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [2]:
matrix_3x3 = np.arange(9).reshape(3, 3) 
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
identity_matrix = np.eye(3)
identity_matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
array_3d = np.random.rand(3, 3, 3)
array_3d


array([[[0.69944987, 0.43138657, 0.49618547],
        [0.89352495, 0.23284148, 0.53835247],
        [0.46485105, 0.86791756, 0.15578384]],

       [[0.57395205, 0.6051843 , 0.97722476],
        [0.69312323, 0.40387132, 0.43315201],
        [0.16166722, 0.24387236, 0.6605029 ]],

       [[0.49444436, 0.86387839, 0.00487584],
        [0.91045812, 0.18949957, 0.31996179],
        [0.09367125, 0.29845849, 0.95830952]]])

In [5]:
array_10d = np.random.rand(10, 10, 10)
min_array = array_10d.min()
max_array = array_10d.max()
print(min_array)
print(max_array)

0.00038231468720173467
0.9996456377384223


In [6]:
rand_vector = np.random.rand(30)
rand_vector.mean()

np.float64(0.5313268034928184)

In [7]:
x = np.random.rand(5, 5)
y = (x-np.min(x))/(np.max(x)-np.min(x))
y

array([[0.40951449, 0.32311434, 0.99115493, 0.80530248, 0.63631538],
       [0.31028953, 0.80169798, 0.37271602, 0.64626784, 0.07913255],
       [0.96899397, 1.        , 0.9021172 , 0.        , 0.8999946 ],
       [0.85414749, 0.86774226, 0.41082454, 0.84910334, 0.1838644 ],
       [0.99152547, 0.83147287, 0.58797457, 0.24126906, 0.66314371]])

In [8]:
a = np.random.rand(5, 3)
b = np.random.rand(3, 2)
c = np.dot(a, b)
c

array([[0.88474598, 0.53725591],
       [0.48445739, 0.31113153],
       [0.93347923, 0.45722657],
       [1.15403793, 0.38616416],
       [0.59938822, 0.32516597]])

In [9]:
a = np.random.rand(3, 3)
b = np.random.rand(3, 3)
c = np.dot(a, b)
c

array([[0.84510785, 0.94600486, 1.16906322],
       [0.61739608, 0.26844697, 0.56068424],
       [0.73547364, 0.36032749, 0.78619961]])

In [10]:
matrix_4x4 = np.random.rand(4, 4)
print(matrix_4x4)
transpose_4x4 = matrix_4x4.T
print(transpose_4x4)

[[0.16641416 0.3512128  0.79141891 0.67402313]
 [0.65501824 0.84192028 0.39598401 0.0369465 ]
 [0.49778701 0.89689017 0.84894765 0.67406742]
 [0.91644361 0.26794567 0.76471415 0.16808494]]
[[0.16641416 0.65501824 0.49778701 0.91644361]
 [0.3512128  0.84192028 0.89689017 0.26794567]
 [0.79141891 0.39598401 0.84894765 0.76471415]
 [0.67402313 0.0369465  0.67406742 0.16808494]]


In [11]:
matrix_3x3_determinant = np.random.rand(3, 3)
determinant = np.linalg.det(matrix_3x3_determinant)
determinant

np.float64(0.12319321714523908)

In [12]:
matrix_3x4 = np.random.rand(3, 4)
matrix_4x3 = np.random.rand(4, 3)
mult = np.dot(matrix_3x4, matrix_4x3)
mult 

array([[0.97487583, 0.71113176, 1.00397247],
       [1.48574829, 1.11206259, 1.40539517],
       [1.30602156, 0.74123065, 1.24919196]])

In [13]:
matrix_3x3 = np.random.rand(3, 3)
vector_3 = np.random.rand(3, 1)
mult = np.dot(matrix_3x3, vector_3)
mult 

array([[1.18665331],
       [1.14779787],
       [1.01386168]])

In [14]:
matrix_3x3 = np.random.rand(3, 3)
vector_3 = np.random.rand(3, 1)
x_solution = np.linalg.solve(matrix_3x3, vector_3)
x_solution 

array([[-9.09396466],
       [ 6.30344893],
       [ 3.96024561]])

In [15]:
matrix_5x5 = np.random.rand(5, 5)
row_sum = matrix_5x5.sum(axis = 1)
column_sum = matrix_5x5.sum(axis = 0)
print(matrix_5x5)
print(row_sum)
print(column_sum)

[[0.98249496 0.96785857 0.66384373 0.2939892  0.87694382]
 [0.72912503 0.19357034 0.16164956 0.31706441 0.44445388]
 [0.79937155 0.52044422 0.05431738 0.45571473 0.44561568]
 [0.18585083 0.05917686 0.96882955 0.11775548 0.25073987]
 [0.74165097 0.23268532 0.8725693  0.73680095 0.49788339]]
[3.78513029 1.84586322 2.27546356 1.58235259 3.08158994]
[3.43849335 1.97373532 2.72120952 1.92132477 2.51563663]
