In [10]:
import numpy as np
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [13]:
matrix_3x3 = np.arange(9).reshape(3, 3) 
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
identity_matrix = np.eye(3)
identity_matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
array_3d = np.random.rand(3, 3, 3)
array_3d


array([[[0.08325826, 0.18855016, 0.7844339 ],
        [0.20716152, 0.00167996, 0.06542806],
        [0.58313703, 0.90854133, 0.18332409]],

       [[0.24770627, 0.84425499, 0.36985115],
        [0.56742166, 0.11342635, 0.86598121],
        [0.84363185, 0.39389128, 0.8780098 ]],

       [[0.52566143, 0.87421162, 0.1272835 ],
        [0.1313663 , 0.53011734, 0.72627635],
        [0.64419233, 0.39406697, 0.02113098]]])

In [62]:
array_10d = np.random.rand(10, 10, 10)
min_array = array_10d.min()
max_array = array_10d.max()
print(min_array)
print(max_array)

0.000815893577553295
0.9999373914028741


In [75]:
rand_vector = np.random.rand(30)
rand_vector.mean()

np.float64(0.47077162144111423)

In [79]:
x = np.random.rand(5, 5)
y = (x-np.min(x))/(np.max(x)-np.min(x))
y

array([[0.        , 0.94758972, 1.        , 0.32706772, 0.40360055],
       [0.96914041, 0.87333257, 0.28990989, 0.09063452, 0.96830426],
       [0.25182269, 0.95401697, 0.89148844, 0.55033075, 0.08663684],
       [0.19951925, 0.06959316, 0.14737816, 0.79821009, 0.92333624],
       [0.07291198, 0.26999844, 0.93269288, 0.39047159, 0.17900395]])

In [82]:
a = np.random.rand(5, 3)
b = np.random.rand(3, 2)
c = np.dot(a, b)
c

array([[0.37980916, 0.28880486],
       [0.48057471, 0.1873325 ],
       [0.62704111, 0.15742005],
       [0.95874868, 0.58349527],
       [0.73940465, 0.18425371]])

In [83]:
a = np.random.rand(3, 3)
b = np.random.rand(3, 3)
c = np.dot(a, b)
c

array([[0.68442183, 0.41375276, 0.4928678 ],
       [0.44438331, 0.31402659, 0.36765302],
       [0.62201723, 0.95247905, 1.04610605]])

In [84]:
matrix_4x4 = np.random.rand(4, 4)
print(matrix_4x4)
transpose_4x4 = matrix_4x4.T
print(transpose_4x4)

[[0.29852161 0.40795094 0.90647017 0.60722038]
 [0.00458834 0.75685329 0.93293924 0.66527317]
 [0.20843884 0.05873905 0.64980558 0.69450912]
 [0.32809631 0.1899446  0.88320972 0.66581981]]
[[0.29852161 0.00458834 0.20843884 0.32809631]
 [0.40795094 0.75685329 0.05873905 0.1899446 ]
 [0.90647017 0.93293924 0.64980558 0.88320972]
 [0.60722038 0.66527317 0.69450912 0.66581981]]


In [90]:
matrix_3x3_determinant = np.random.rand(3, 3)
determinant = np.linalg.det(matrix_3x3_determinant)
determinant

np.float64(0.013843587287457585)

In [91]:
matrix_3x4 = np.random.rand(3, 4)
matrix_4x3 = np.random.rand(4, 3)
mult = np.dot(matrix_3x4, matrix_4x3)
mult 

array([[0.33982301, 1.19393037, 0.74334177],
       [0.38381138, 0.98397276, 0.8562808 ],
       [0.60653732, 1.40673642, 1.21905618]])

In [93]:
matrix_3x3 = np.random.rand(3, 3)
vector_3 = np.random.rand(3, 1)
mult = np.dot(matrix_3x3, vector_3)
mult 

array([[0.7324373 ],
       [0.64239441],
       [0.60466166]])

In [94]:
matrix_3x3 = np.random.rand(3, 3)
vector_3 = np.random.rand(3, 1)
x_solution = np.linalg.solve(matrix_3x3, vector_3)
x_solution 

array([[-0.13695251],
       [ 2.15844093],
       [-2.11667678]])

In [98]:
matrix_5x5 = np.random.rand(5, 5)
row_sum = matrix_5x5.sum(axis = 1)
column_sum = matrix_5x5.sum(axis = 0)
print(matrix_5x5)
print(row_sum)
print(column_sum)

[[0.45417696 0.45171906 0.79463109 0.47214849 0.16509762]
 [0.65871075 0.98635059 0.7702009  0.15568915 0.70861992]
 [0.71946304 0.17764674 0.91260269 0.36849036 0.9368808 ]
 [0.26885513 0.58726792 0.7516461  0.6025574  0.65344625]
 [0.13882185 0.62886602 0.57266817 0.75435034 0.37099337]]
[2.33777322 3.27957131 3.11508363 2.86377281 2.46569973]
[2.24002773 2.83185033 3.80174895 2.35323573 2.83503796]
