In [1]:
import numpy as np
def far_to_cel(f):
    return (f - 32) * 5 / 9
f_to_c  = np.vectorize(far_to_cel)
far = np.array([32, 68, 100, 212, 77])
cel = f_to_c(far)
cel


array([  0.        ,  20.        ,  37.77777778, 100.        ,
        25.        ])

In [3]:
import numpy as np
def powerr(a, b):
    return a ** b
exp = np.vectorize(powerr)
base = np.array([2,3,4,5])
exponent = np.array([1,2,3,4]) 
result = exp(base, exponent)
result

array([  2,   9,  64, 625])

In [5]:
import numpy as np
A = np.array([[4, 5, 6], [3, -1, 1], [2, 1, -2]]) 
b = np.array([7, 4, 5])
x = np.linalg.solve(A, b)
x

array([ 1.7027027 ,  0.62162162, -0.48648649])

In [6]:
import numpy as np
A = np.array([[10, -2, 3], [-2, 8, -1], [3, -1, 6]]) 
b = np.array([12, -5, 15])
x = np.linalg.solve(A, b)
x

array([ 0.48963731, -0.2253886 ,  2.21761658])